### ISSUE TITLE
The implement about changing the MIL classifier to TransMIL

### ISSUE THREAD

**Issue by laico12345** [Zero-We/BCL#7]
Hi, I am facing a problem: TransMIL's attention is too large to return and utilize, I want to make sure about the TransMIL + BCL implement detail, which attention do you use exactly, is the NystromAttention return? If possible, could you provide the TransMIL-based version?

**Comment by zihou98** [comment]
Hi, I am sorry that I could not provide TransMIL-based version recently, because I am busy with other things now. I can't understand why "TransMIL's attention is too large to return and utilize". In fact, we use the Nystrom Attention to assign pseudo labels to the patches. TransMIl first pads the feature tokens, so the dimension of the returned attn will be larger than the number of patches. I have listed some screenshots of my previous code (it may contains errors) as below, hoping to help you.
![shot1](https://github.com/Zero-We/BCL/assets/39939845/401d6599-b3c0-4768-b29c-25d5ab03bf9f)
![shot2](https://github.com/Zero-We/BCL/assets/39939845/aa757d03-8c3a-4349-bfdd-aa159d6e808d)

**Comment by laico12345** [comment]
Thanks for your reply!
It helps a lot.

**Comment by laico12345** [comment]
"TransMIL's attention is too large to return and utilize". This means I use the original code from nystorm_attention to return then the size is too large it needs 29 gigabytes of space in GPU. But if I use the mean to return, the problem is solved !! Again thanks for the reply.
